"""
PMIR-Net-Lite: Simulated Distorted Speech/Transcript Generator.
Procedurally generates synthetic benchmark datasets across 4 severity levels:
clean, mild, moderate, and severe.

RESPONSIBLE USE & ETHICS NOTICE:
All records generated by this module are simulated mathematical approximations of
phonetic noise, stuttering, and ASR transcription errors.
They are NOT authentic clinical patient recordings.
Every generated row carries the explicit label: "data_source": "SIMULATED".
"""

import json
import random
import re
from typing import Dict, List, Any, Optional


class TranscriptDistortionSimulator:
    """
    Simulates speech transcript distortions across 4 severity levels:
      - clean: Standard phrasing, minimal punctuation/casing variance.
      - mild: Light stuttering ('p-p-please'), mild vowel elongation ('waater'), dropped leading articles.
      - moderate: Phonetic consonant shifts ('wader', 'blankit'), slurring, filler words ('uh', 'um').
      - severe: Heavy phoneme drops, severe stutter fragments, high acoustic ASR substitutions.
    """

    # Common consonant substitution pairs mimicking dysarthric / acoustic ASR confusion
    CONSONANT_SUBS = {
        "t": ["d", ""],
        "d": ["t", "th"],
        "p": ["b", "v"],
        "b": ["p", "v"],
        "k": ["g", ""],
        "g": ["k"],
        "s": ["th", "sh", "z"],
        "z": ["s"],
        "f": ["v", "th"],
        "v": ["f", "w"],
        "w": ["v", "r"],
        "r": ["w", "l"],
        "l": ["r", "w"],
        "th": ["d", "t", "f"]
    }

    # Common ASR acoustic / homophonic confusions
    ASR_CONFUSIONS = {
        "water": ["wader", "wa-er", "wotta", "worter"],
        "cold": ["gold", "kold", "col"],
        "hot": ["hart", "ot", "hat"],
        "pain": ["pane", "bane", "pen"],
        "help": ["hewp", "hep", "halp", "elp"],
        "blanket": ["blankit", "banket", "blanget"],
        "medicine": ["medsin", "pills", "medz", "medisin"],
        "restroom": ["bathroom", "washroom", "rest room", "bafrum"],
        "turn": ["tern", "tun", "turm"],
        "lights": ["lites", "lies", "lits"],
        "sleep": ["seep", "slep", "zeep"],
        "hungry": ["hungri", "hungee", "ungry"],
        "doctor": ["doc", "docta", "dock"],
        "call": ["col", "kawl", "ca"],
        "emergency": ["emergensy", "emerg", "urgent help"],
        "music": ["musick", "muzik", "museek"],
        "pillow": ["pillo", "pilloow", "pilloe"]
    }

    def __init__(self, seed: Optional[int] = 42):
        if seed is not None:
            random.seed(seed)

    def apply_clean(self, text: str) -> str:
        """Returns clean variant with minor punctuation/case variations."""
        text = text.lower()
        if random.random() < 0.3:
            text = text.capitalize()
        if random.random() < 0.2:
            text = text + "."
        return text

    def apply_mild(self, text: str) -> str:
        """
        Applies mild distortions:
        - Light stuttering on first word ('w-w-water')
        - Mild vowel stretching ('waater')
        - Dropping short filler words like 'i', 'a', 'the'
        """
        words = text.lower().split()
        if not words:
            return text

        # 1. Dropping initial pronoun/article
        if len(words) > 2 and words[0] in ("i", "can", "please", "a", "the") and random.random() < 0.5:
            words = words[1:]

        # 2. Light stutter on random word
        target_idx = random.randint(0, len(words) - 1)
        w = words[target_idx]
        if len(w) > 2 and random.random() < 0.6:
            lead = w[0]
            words[target_idx] = f"{lead}-{lead}-{w}"

        # 3. Mild vowel elongation
        if random.random() < 0.4:
            elong_idx = random.randint(0, len(words) - 1)
            w = words[elong_idx]
            vowels = [m.start() for m in re.finditer(r"[aeiou]", w)]
            if vowels:
                v_pos = random.choice(vowels)
                v_char = w[v_pos]
                words[elong_idx] = w[:v_pos] + (v_char * 2) + w[v_pos + 1:]

        return " ".join(words)

    def apply_moderate(self, text: str) -> str:
        """
        Applies moderate distortions:
        - ASR acoustic word substitutions
        - Consonant shifts
        - Insertion of speech fillers ('uh', 'um')
        - Ellipsis / hesitation markers
        """
        words = text.lower().split()
        if not words:
            return text

        # 1. Substitute from acoustic confusion dictionary
        new_words = []
        for w in words:
            clean_w = re.sub(r"[^\w]", "", w)
            if clean_w in self.ASR_CONFUSIONS and random.random() < 0.7:
                conf = random.choice(self.ASR_CONFUSIONS[clean_w])
                new_words.append(conf)
            else:
                new_words.append(w)
        words = new_words

        # 2. Consonant shifting
        shifted_words = []
        for w in words:
            chars = list(w)
            for i, ch in enumerate(chars):
                if ch in self.CONSONANT_SUBS and random.random() < 0.25:
                    sub = random.choice(self.CONSONANT_SUBS[ch])
                    chars[i] = sub
            shifted_words.append("".join(chars))
        words = shifted_words

        # 3. Insert filler sound
        if random.random() < 0.5:
            filler = random.choice(["uh", "um", "ah"])
            insert_pos = random.randint(0, len(words))
            words.insert(insert_pos, filler)

        # 4. Multi-dot stutter
        if random.random() < 0.4 and words:
            w_idx = random.randint(0, len(words) - 1)
            if len(words[w_idx]) > 2:
                words[w_idx] = f"{words[w_idx][:2]}...{words[w_idx]}"

        return " ".join(words)

    def apply_severe(self, text: str) -> str:
        """
        Applies severe distortions:
        - Heavy phoneme truncation / dropping syllables
        - Extreme stutters ('w-w-wa...er')
        - Partial phrase fragmentation (omitting key verbs/nouns)
        - Heavy acoustic corruption
        """
        words = text.lower().split()
        if not words:
            return text

        # 1. Aggressive word dropping (keep only 1 or 2 core content words)
        if len(words) > 2:
            # retain the most salient content word (usually last or second)
            content_candidates = [w for w in words if w not in ("i", "am", "the", "a", "can", "to", "my")]
            if content_candidates:
                words = content_candidates[:2]
            else:
                words = words[-2:]

        corrupted = []
        for w in words:
            clean_w = re.sub(r"[^\w]", "", w)
            if clean_w in self.ASR_CONFUSIONS and random.random() < 0.8:
                w = random.choice(self.ASR_CONFUSIONS[clean_w])

            # Truncate end of word or drop middle phonemes
            if len(w) > 4 and random.random() < 0.7:
                cut_point = random.randint(2, len(w) - 1)
                w = w[:cut_point] + "-" + w[cut_point + 1:]

            # Heavy prefix stutter
            if len(w) > 2 and random.random() < 0.6:
                prefix = w[0]
                w = f"{prefix}-{prefix}-{prefix}...{w}"

            corrupted.append(w)

        # Occasional filler sound insertion
        if random.random() < 0.6:
            corrupted.insert(0, random.choice(["uh", "um", "er"]))

        return " ".join(corrupted)

    def generate_benchmark(
        self,
        intents_path: str,
        output_path: Optional[str] = None,
        samples_per_intent: int = 12
    ) -> Dict[str, Any]:
        """
        Generates full simulated benchmark across 4 severity tiers for all intents.
        Guarantees that every row has 'data_source': 'SIMULATED'.
        """
        with open(intents_path, "r", encoding="utf-8") as f:
            intents_data = json.load(f)

        intents = intents_data.get("intents", [])
        dataset: List[Dict[str, Any]] = []

        severities = ["clean", "mild", "moderate", "severe"]
        # Per intent, evenly distribute across severities
        samples_per_severity = max(1, samples_per_intent // len(severities))

        row_id = 1
        for intent in intents:
            intent_id = intent["id"]
            base_phrases = intent.get("base_phrases", [])

            for sev in severities:
                for _ in range(samples_per_severity):
                    base_phrase = random.choice(base_phrases)

                    if sev == "clean":
                        distorted = self.apply_clean(base_phrase)
                    elif sev == "mild":
                        distorted = self.apply_mild(base_phrase)
                    elif sev == "moderate":
                        distorted = self.apply_moderate(base_phrase)
                    else:  # severe
                        distorted = self.apply_severe(base_phrase)

                    dataset.append({
                        "id": f"SIM_{row_id:04d}",
                        "data_source": "SIMULATED",
                        "severity": sev,
                        "ground_truth_intent": intent_id,
                        "canonical_base_phrase": base_phrase,
                        "distorted_transcript": distorted,
                        "urgency": intent.get("urgency", "medium")
                    })
                    row_id += 1

        output_payload = {
            "metadata": {
                "dataset_name": "PMIR-Net-Lite Simulated Imperfect Speech Benchmark",
                "version": "1.0.0",
                "data_source": "SIMULATED",
                "responsible_use_notice": (
                    "Assistive prototype benchmark only. All samples procedurally simulated. "
                    "No clinical validity or authentic patient data."
                ),
                "total_samples": len(dataset),
                "total_intents": len(intents),
                "severity_distribution": {
                    sev: sum(1 for r in dataset if r["severity"] == sev)
                    for sev in severities
                }
            },
            "samples": dataset
        }

        if output_path:
            with open(output_path, "w", encoding="utf-8") as f:
                json.dump(output_payload, f, indent=2)

        return output_payload

